project:
  output-dir: _output
  type: website

website:
  title: "Aerial Mzansi + Quarto + Shinylive"
  navbar:
    left:
    - text: Aerial Mzansi Website
      href: https://www.aerialmzansi.com/
    right:
      - icon: github
        href: https://github.com/luisdza/aerialmzansi-shiny
  twitter-card: true

format:
  html:
    theme: cosmo
    code-link: true
    callout-appearance: simple
    toc: true
    author-meta: "Luis de Sousa"
    description-meta: "Aerial Mzansi"