project:
  type: website
  output-dir: docs
  render:
    - /index.qmd

website:
  title: "Aerial Mzansi + Quarto + Shinylive"
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/luisdza/aerialmzansi-shiny

format:
  html:
    toc: true
